version: '3.1'

services:
  db:
    image: mysql:8.0.14
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
  web:
    build: .
    restart: always
    command: bash -c "sleep 10; python app.py"
    volumes:
      - .:/project
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    depends_on:
      - db

volumes:
  db-data:
